import type { AnyActivityData } from '@/core/activity-engine/types'

export const alphabetActivities: AnyActivityData[] = [
  // ==========================================
  // NHÓM 1: Nguyên âm cơ bản (a, e, i, o, u, y)
  // ==========================================
  {
    id: 'alphabet_g1_explore',
    title: 'Khám Phá Chữ Nhóm 1',
    module: 'alphabet',
    template: 'explore',
    ageMin: 3,
    learningGoal: 'Bé làm quen các nguyên âm cơ bản: a, e, i, o, u, y',
    promptText: 'Chạm vào từng chữ cái để nghe phát âm nhé!',
    promptAudio: 'pikachu_greeting',
    rewardStars: 1,
    items: [
      { id: 'let_a', label: 'Chữ a', audioId: 'letter_a', displayChar: 'A a', subLabel: 'Cái ao', color: '#FFEBEE' },
      { id: 'let_e', label: 'Chữ e', audioId: 'letter_e', displayChar: 'E e', subLabel: 'Em bé', color: '#E3F2FD' },
      { id: 'let_i', label: 'Chữ i', audioId: 'letter_i', displayChar: 'I i', subLabel: 'Con heo', color: '#FFFDE7' },
      { id: 'let_o', label: 'Chữ o', audioId: 'letter_o', displayChar: 'O o', subLabel: 'Con ong', color: '#F3E5F5' },
      { id: 'let_u', label: 'Chữ u', audioId: 'letter_u', displayChar: 'U u', subLabel: 'Đôi ủng', color: '#E8F5E9' },
      { id: 'let_y', label: 'Chữ y', audioId: 'letter_y', displayChar: 'Y y', subLabel: 'Y tá', color: '#FFF3E0' },
    ],
  },
  {
    id: 'alphabet_g1_listen_pick',
    title: 'Tìm Chữ Nhóm 1',
    module: 'alphabet',
    template: 'listen_pick',
    ageMin: 3,
    learningGoal: 'Bé lắng nghe âm thanh và chọn đúng chữ cái tương ứng trong Nhóm 1',
    promptText: 'Bạn chạm vào chữ a nhé!',
    promptAudio: 'prompt_find_letter_a',
    targetId: 'choice_a',
    rewardStars: 1,
    choices: [
      { id: 'choice_a', label: 'Chữ a', audioId: 'letter_a', color: '#FF5252', icon: '🅰️', isCorrect: true },
      { id: 'choice_e', label: 'Chữ e', audioId: 'letter_e', color: '#448AFF', icon: 'E', isCorrect: false },
      { id: 'choice_o', label: 'Chữ o', audioId: 'letter_o', color: '#FED000', icon: 'O', isCorrect: false },
    ],
  },
  {
    id: 'alphabet_g1_match',
    title: 'Ghép Chữ Với Hình Nhóm 1',
    module: 'alphabet',
    template: 'match',
    ageMin: 3,
    learningGoal: 'Bé liên kết mặt chữ với từ và hình ảnh minh họa quen thuộc',
    promptText: 'Bé ghép chữ với hình phù hợp nhé!',
    promptAudio: 'prompt_match_letter_word',
    rewardStars: 1,
    pairs: [
      { id: 'pair_a', label: 'Chữ a', audioId: 'letter_a_word', leftType: 'letter', leftValue: 'A a', rightType: 'word', rightValue: '🌊 Cái ao' },
      { id: 'pair_e', label: 'Chữ e', audioId: 'letter_e_word', leftType: 'letter', leftValue: 'E e', rightType: 'word', rightValue: '👶 Em bé' },
      { id: 'pair_i', label: 'Chữ i', audioId: 'letter_i_word', leftType: 'letter', leftValue: 'I i', rightType: 'word', rightValue: '🐷 Con heo' },
      { id: 'pair_o', label: 'Chữ o', audioId: 'letter_o_word', leftType: 'letter', leftValue: 'O o', rightType: 'word', rightValue: '🐝 Con ong' },
    ],
  },

  // ==========================================
  // NHÓM 2: Nguyên âm có dấu (ă, â, ê, ô, ơ, ư)
  // ==========================================
  {
    id: 'alphabet_g2_explore',
    title: 'Khám Phá Chữ Nhóm 2',
    module: 'alphabet',
    template: 'explore',
    ageMin: 3,
    learningGoal: 'Bé làm quen các nguyên âm có mũ và móc: ă, â, ê, ô, ơ, ư',
    promptText: 'Chạm vào từng chữ cái để nghe phát âm nhé!',
    promptAudio: 'pikachu_greeting',
    rewardStars: 1,
    items: [
      { id: 'let_a_breve', label: 'Chữ á (ă)', audioId: 'letter_a_breve', displayChar: 'Ă ă', subLabel: 'Bé ăn cơm', color: '#FFEBEE' },
      { id: 'let_a_circumflex', label: 'Chữ ớ (â)', audioId: 'letter_a_circumflex', displayChar: 'Â â', subLabel: 'Ấm nước', color: '#E3F2FD' },
      { id: 'let_e_circumflex', label: 'Chữ ê', audioId: 'letter_e_circumflex', displayChar: 'Ê ê', subLabel: 'Con ếch', color: '#FFFDE7' },
      { id: 'let_o_circumflex', label: 'Chữ ô', audioId: 'letter_o_circumflex', displayChar: 'Ô ô', subLabel: 'Ô tô', color: '#F3E5F5' },
      { id: 'let_o_horn', label: 'Chữ ơ', audioId: 'letter_o_horn', displayChar: 'Ơ ơ', subLabel: 'Quả ớt', color: '#E8F5E9' },
      { id: 'let_u_horn', label: 'Chữ ư', audioId: 'letter_u_horn', displayChar: 'Ư ư', subLabel: 'Sư tử', color: '#FFF3E0' },
    ],
  },
  {
    id: 'alphabet_g2_listen_pick',
    title: 'Tìm Chữ Nhóm 2',
    module: 'alphabet',
    template: 'listen_pick',
    ageMin: 3,
    learningGoal: 'Bé lắng nghe âm thanh và chọn đúng chữ cái tương ứng trong Nhóm 2',
    promptText: 'Bạn chạm vào chữ ô nhé!',
    promptAudio: 'prompt_find_letter_o_circumflex',
    targetId: 'choice_o_hat',
    rewardStars: 1,
    choices: [
      { id: 'choice_e_hat', label: 'Chữ ê', audioId: 'letter_e_circumflex', color: '#66BB6A', icon: 'Ê', isCorrect: false },
      { id: 'choice_o_hat', label: 'Chữ ô', audioId: 'letter_o_circumflex', color: '#AB47BC', icon: 'Ô', isCorrect: true },
      { id: 'choice_u_horn', label: 'Chữ ư', audioId: 'letter_u_horn', color: '#448AFF', icon: 'Ư', isCorrect: false },
    ],
  },
  {
    id: 'alphabet_g2_match',
    title: 'Ghép Chữ Với Hình Nhóm 2',
    module: 'alphabet',
    template: 'match',
    ageMin: 3,
    learningGoal: 'Bé liên kết chữ có dấu với các từ ngữ thân quen',
    promptText: 'Bé ghép chữ với hình phù hợp nhé!',
    promptAudio: 'prompt_match_letter_word',
    rewardStars: 1,
    pairs: [
      { id: 'pair_a_breve', label: 'Chữ ă', audioId: 'letter_a_breve_word', leftType: 'letter', leftValue: 'Ă ă', rightType: 'word', rightValue: '🍚 Bé ăn' },
      { id: 'pair_e_circumflex', label: 'Chữ ê', audioId: 'letter_e_circumflex_word', leftType: 'letter', leftValue: 'Ê ê', rightType: 'word', rightValue: '🐸 Con ếch' },
      { id: 'pair_o_circumflex', label: 'Chữ ô', audioId: 'letter_o_circumflex_word', leftType: 'letter', leftValue: 'Ô ô', rightType: 'word', rightValue: '🚗 Ô tô' },
      { id: 'pair_o_horn', label: 'Chữ ơ', audioId: 'letter_o_horn_word', leftType: 'letter', leftValue: 'Ơ ơ', rightType: 'word', rightValue: '🌶️ Quả ớt' },
    ],
  },

  // ==========================================
  // NHÓM 3: Phụ âm quen thuộc (m, n, t, l, h, c)
  // ==========================================
  {
    id: 'alphabet_g3_explore',
    title: 'Khám Phá Chữ Nhóm 3',
    module: 'alphabet',
    template: 'explore',
    ageMin: 3,
    learningGoal: 'Bé làm quen các phụ âm cơ bản: m, n, t, l, h, c',
    promptText: 'Chạm vào từng chữ cái để nghe phát âm nhé!',
    promptAudio: 'pikachu_greeting',
    rewardStars: 1,
    items: [
      { id: 'let_m', label: 'Chữ mờ', audioId: 'letter_m', displayChar: 'M m', subLabel: 'Con mèo', color: '#FFEBEE' },
      { id: 'let_n', label: 'Chữ nờ', audioId: 'letter_n', displayChar: 'N n', subLabel: 'Cái nón', color: '#E3F2FD' },
      { id: 'let_t', label: 'Chữ tờ', audioId: 'letter_t', displayChar: 'T t', subLabel: 'Con tàu', color: '#FFFDE7' },
      { id: 'let_l', label: 'Chữ lờ', audioId: 'letter_l', displayChar: 'L l', subLabel: 'Chiếc lá', color: '#F3E5F5' },
      { id: 'let_h', label: 'Chữ hờ', audioId: 'letter_h', displayChar: 'H h', subLabel: 'Bông hoa', color: '#E8F5E9' },
      { id: 'let_c', label: 'Chữ cờ', audioId: 'letter_c', displayChar: 'C c', subLabel: 'Con cá', color: '#FFF3E0' },
    ],
  },
  {
    id: 'alphabet_g3_listen_pick',
    title: 'Tìm Chữ Nhóm 3',
    module: 'alphabet',
    template: 'listen_pick',
    ageMin: 3,
    learningGoal: 'Bé nghe âm phụ âm m, n, t, l, h, c và chọn đúng chữ cái',
    promptText: 'Bạn chạm vào chữ mờ nhé!',
    promptAudio: 'prompt_find_letter_m',
    targetId: 'choice_m',
    rewardStars: 1,
    choices: [
      { id: 'choice_n', label: 'Chữ nờ', audioId: 'letter_n', color: '#448AFF', icon: 'N', isCorrect: false },
      { id: 'choice_m', label: 'Chữ mờ', audioId: 'letter_m', color: '#FF5252', icon: 'M', isCorrect: true },
      { id: 'choice_c', label: 'Chữ cờ', audioId: 'letter_c', color: '#FED000', icon: 'C', isCorrect: false },
    ],
  },
  {
    id: 'alphabet_g3_match',
    title: 'Ghép Chữ Với Hình Nhóm 3',
    module: 'alphabet',
    template: 'match',
    ageMin: 3,
    learningGoal: 'Bé liên kết chữ m, c, h, l với các con vật và đồ vật yêu thích',
    promptText: 'Bé ghép chữ với hình phù hợp nhé!',
    promptAudio: 'prompt_match_letter_word',
    rewardStars: 1,
    pairs: [
      { id: 'pair_m', label: 'Chữ m', audioId: 'letter_m_word', leftType: 'letter', leftValue: 'M m', rightType: 'word', rightValue: '🐱 Con mèo' },
      { id: 'pair_c', label: 'Chữ c', audioId: 'letter_c_word', leftType: 'letter', leftValue: 'C c', rightType: 'word', rightValue: '🐟 Con cá' },
      { id: 'pair_h', label: 'Chữ h', audioId: 'letter_h_word', leftType: 'letter', leftValue: 'H h', rightType: 'word', rightValue: '🌸 Bông hoa' },
      { id: 'pair_l', label: 'Chữ l', audioId: 'letter_l_word', leftType: 'letter', leftValue: 'L l', rightType: 'word', rightValue: '🍃 Chiếc lá' },
    ],
  },

  // ==========================================
  // NHÓM 4: Phụ âm tiếp theo (b, p, v, x, s, r)
  // ==========================================
  {
    id: 'alphabet_g4_explore',
    title: 'Khám Phá Chữ Nhóm 4',
    module: 'alphabet',
    template: 'explore',
    ageMin: 3,
    learningGoal: 'Bé làm quen các phụ âm tiếp theo: b, p, v, x, s, r',
    promptText: 'Chạm vào từng chữ cái để nghe phát âm nhé!',
    promptAudio: 'pikachu_greeting',
    rewardStars: 1,
    items: [
      { id: 'let_b', label: 'Chữ bờ', audioId: 'letter_b', displayChar: 'B b', subLabel: 'Quả bóng', color: '#FFEBEE' },
      { id: 'let_p', label: 'Chữ pờ', audioId: 'letter_p', displayChar: 'P p', subLabel: 'Cục pin', color: '#E3F2FD' },
      { id: 'let_v', label: 'Chữ vờ', audioId: 'letter_v', displayChar: 'V v', subLabel: 'Con vịt', color: '#FFFDE7' },
      { id: 'let_x', label: 'Chữ xờ', audioId: 'letter_x', displayChar: 'X x', subLabel: 'Xe hơi', color: '#F3E5F5' },
      { id: 'let_s', label: 'Chữ sờ', audioId: 'letter_s', displayChar: 'S s', subLabel: 'Ngôi sao', color: '#E8F5E9' },
      { id: 'let_r', label: 'Chữ rờ', audioId: 'letter_r', displayChar: 'R r', subLabel: 'Con rùa', color: '#FFF3E0' },
    ],
  },
  {
    id: 'alphabet_g4_listen_pick',
    title: 'Tìm Chữ Nhóm 4',
    module: 'alphabet',
    template: 'listen_pick',
    ageMin: 3,
    learningGoal: 'Bé nhận biết chữ b, p, v, x, s, r qua phát âm chuẩn',
    promptText: 'Bạn chạm vào chữ bờ nhé!',
    promptAudio: 'prompt_find_letter_b',
    targetId: 'choice_b',
    rewardStars: 1,
    choices: [
      { id: 'choice_b', label: 'Chữ bờ', audioId: 'letter_b', color: '#448AFF', icon: '🅱️', isCorrect: true },
      { id: 'choice_p', label: 'Chữ pờ', audioId: 'letter_p', color: '#AB47BC', icon: 'P', isCorrect: false },
      { id: 'choice_v', label: 'Chữ vờ', audioId: 'letter_v', color: '#66BB6A', icon: 'V', isCorrect: false },
    ],
  },
  {
    id: 'alphabet_g4_match',
    title: 'Ghép Chữ Với Hình Nhóm 4',
    module: 'alphabet',
    template: 'match',
    ageMin: 3,
    learningGoal: 'Bé ghép chữ cái với các hình minh họa quen thuộc',
    promptText: 'Bé ghép chữ với hình phù hợp nhé!',
    promptAudio: 'prompt_match_letter_word',
    rewardStars: 1,
    pairs: [
      { id: 'pair_b', label: 'Chữ b', audioId: 'letter_b_word', leftType: 'letter', leftValue: 'B b', rightType: 'word', rightValue: '⚽ Quả bóng' },
      { id: 'pair_v', label: 'Chữ v', audioId: 'letter_v_word', leftType: 'letter', leftValue: 'V v', rightType: 'word', rightValue: '🦆 Con vịt' },
      { id: 'pair_s', label: 'Chữ s', audioId: 'letter_s_word', leftType: 'letter', leftValue: 'S s', rightType: 'word', rightValue: '⭐ Ngôi sao' },
      { id: 'pair_r', label: 'Chữ r', audioId: 'letter_r_word', leftType: 'letter', leftValue: 'R r', rightType: 'word', rightValue: '🐢 Con rùa' },
    ],
  },

  // ==========================================
  // NHÓM 5: Phụ âm dễ nhầm (d, đ, g, k, q)
  // ==========================================
  {
    id: 'alphabet_g5_explore',
    title: 'Khám Phá Chữ Nhóm 5',
    module: 'alphabet',
    template: 'explore',
    ageMin: 3,
    learningGoal: 'Bé làm quen các phụ âm đặc biệt và dễ nhầm: d, đ, g, k, q',
    promptText: 'Chạm vào từng chữ cái để nghe phát âm nhé!',
    promptAudio: 'pikachu_greeting',
    rewardStars: 1,
    items: [
      { id: 'let_d', label: 'Chữ dờ', audioId: 'letter_d', displayChar: 'D d', subLabel: 'Con dê', color: '#FFEBEE' },
      { id: 'let_dd', label: 'Chữ đờ', audioId: 'letter_dd', displayChar: 'Đ đ', subLabel: 'Cây đèn', color: '#E3F2FD' },
      { id: 'let_g', label: 'Chữ gờ', audioId: 'letter_g', displayChar: 'G g', subLabel: 'Con gà', color: '#FFFDE7' },
      { id: 'let_k', label: 'Chữ ca', audioId: 'letter_k', displayChar: 'K k', subLabel: 'Cái kẹo', color: '#F3E5F5' },
      { id: 'let_q', label: 'Chữ cu', audioId: 'letter_q', displayChar: 'Q q', subLabel: 'Cái quạt', color: '#E8F5E9' },
    ],
  },
  {
    id: 'alphabet_g5_listen_pick',
    title: 'Tìm Chữ Nhóm 5',
    module: 'alphabet',
    template: 'listen_pick',
    ageMin: 3,
    learningGoal: 'Bé phân biệt d và đ, nhận biết g, k, q qua âm đọc',
    promptText: 'Bạn chạm vào chữ đờ nhé!',
    promptAudio: 'prompt_find_letter_dd',
    targetId: 'choice_dd',
    rewardStars: 1,
    choices: [
      { id: 'choice_d', label: 'Chữ dờ', audioId: 'letter_d', color: '#FF5252', icon: 'D', isCorrect: false },
      { id: 'choice_dd', label: 'Chữ đờ', audioId: 'letter_dd', color: '#66BB6A', icon: 'Đ', isCorrect: true },
      { id: 'choice_g', label: 'Chữ gờ', audioId: 'letter_g', color: '#448AFF', icon: 'G', isCorrect: false },
    ],
  },
  {
    id: 'alphabet_g5_match',
    title: 'Ghép Chữ Với Hình Nhóm 5',
    module: 'alphabet',
    template: 'match',
    ageMin: 3,
    learningGoal: 'Bé ghép chữ d, đ, g, k với hình ảnh cụ thể để khắc sâu trí nhớ',
    promptText: 'Bé ghép chữ với hình phù hợp nhé!',
    promptAudio: 'prompt_match_letter_word',
    rewardStars: 1,
    pairs: [
      { id: 'pair_d', label: 'Chữ d', audioId: 'letter_d_word', leftType: 'letter', leftValue: 'D d', rightType: 'word', rightValue: '🐐 Con dê' },
      { id: 'pair_dd', label: 'Chữ đ', audioId: 'letter_dd_word', leftType: 'letter', leftValue: 'Đ đ', rightType: 'word', rightValue: '💡 Cái đèn' },
      { id: 'pair_g', label: 'Chữ g', audioId: 'letter_g_word', leftType: 'letter', leftValue: 'G g', rightType: 'word', rightValue: '🐔 Con gà' },
      { id: 'pair_k', label: 'Chữ k', audioId: 'letter_k_word', leftType: 'letter', leftValue: 'K k', rightType: 'word', rightValue: '🍬 Kẹo ngọt' },
    ],
  },
]
